FROM centos:7

RUN yum -y update
RUN yum -y install epel-release
RUN yum -y install gcc gcc-c++ kmod libhdf5-devel perl python-devel python-pip

RUN pip install numpy

WORKDIR /opt/nvidia
ENV CUDA_RUN cuda_6.5.19_linux_64.run
ENV CUDA_URL http://developer.download.nvidia.com/compute/cuda/6_5/rel/installers/$CUDA_RUN
ENV CUDA_75_RUN cuda_7.5.18_linux.run
ENV CUDA_75_URL http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/$CUDA_75_RUN

RUN mkdir installers
RUN curl -o $CUDA_RUN $CUDA_URL && \
    chmod +x $CUDA_RUN && \
    ./$CUDA_RUN -extract=`pwd`/installers
RUN curl -o $CUDA_75_RUN $CUDA_75_URL && \
    chmod +x $CUDA_75_RUN && \
    ./$CUDA_75_RUN -extract=`pwd`/installers

RUN cd installers && \
    ./NVIDIA-Linux-x86_64-352.39.run -s -N --no-kernel-module && \
    ./cuda-linux64-rel-6.5.19-18849900.run -noprompt && \
    cd / && \
    rm -rf /opt/nvidia

ENV CUDA_ROOT /usr/local/cuda
ENV PATH $PATH:$CUDA_ROOT/bin
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$CUDA_ROOT/lib64
